name = "PackageCompilerDebug"
uuid = "a48c22a1-7258-4135-befe-04efb0532d7a"
authors = ["hugo-tam <hugo.ch.tam@gmail.com>"]
version = "0.2.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
